# _config.yml
title: Safal Thapaliya
email: safalthapaliya@gmail.com
description: "Ph.D. student | Graph Neural Networks, Large Language Models, Multi‑modal learning & medical imaging"
baseurl: ""            # when deploying to https://<username>.github.io or your own domain
url: "https://safalthapaliya.com.np"
markdown: kramdown
theme: null            # we’re rolling our own layout/CSS
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap